name: Build and Publish Flow Launcher Vikunja Plugin

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches: [ main ]
    paths-ignore:
      - .github/workflows/*

env:
  python_ver: 3.11

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Plugin Version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'plugin.json'
          prop_path: 'Version'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t ./lib

      - name: Package Plugin
        run: zip -r Flow.Launcher.Plugin.Vikunja.zip . -x '*.git*'

      - name: Publish Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: 'Flow.Launcher.Plugin.Vikunja.zip'
          tag_name: "v${{ steps.version.outputs.prop }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
